# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-09 21:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Academics',
            fields=[
                ('acadId', models.AutoField(primary_key=True, serialize=False)),
                ('subcatId', models.IntegerField(default=0)),
                ('incharge', models.CharField(max_length=45)),
                ('description', models.CharField(max_length=400)),
                ('compid', models.CharField(default='R', max_length=15)),
                ('fidate', models.DateField(default=datetime.datetime(2018, 11, 9, 0, 0))),
                ('status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Authority',
            fields=[
                ('authId', models.AutoField(primary_key=True, serialize=False)),
                ('authName', models.CharField(max_length=45)),
                ('Category', models.CharField(max_length=45)),
                ('email', models.CharField(default='@iiits.in', max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(default='choice', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('eventId', models.AutoField(primary_key=True, serialize=False)),
                ('subcatId', models.IntegerField(default=0)),
                ('eventname', models.CharField(max_length=45)),
                ('nature', models.CharField(max_length=45)),
                ('description', models.CharField(max_length=400)),
                ('status', models.IntegerField(default=0)),
                ('compid', models.CharField(default='R', max_length=15)),
                ('fidate', models.DateField(default=datetime.datetime(2018, 11, 9, 0, 0))),
            ],
        ),
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('hostelId', models.AutoField(primary_key=True, serialize=False)),
                ('subcatId', models.IntegerField(default=0)),
                ('incharge', models.CharField(max_length=45)),
                ('hostelRoomNo', models.CharField(max_length=6)),
                ('description', models.CharField(max_length=400)),
                ('compid', models.CharField(default='R', max_length=15)),
                ('fidate', models.DateField(default=datetime.datetime(2018, 11, 9, 0, 0))),
                ('status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Incharge',
            fields=[
                ('inchargeId', models.AutoField(primary_key=True, serialize=False)),
                ('inchargeName', models.CharField(max_length=45)),
                ('SubCategory', models.CharField(max_length=45)),
                ('email', models.CharField(default='@iiits.in', max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='latestOtp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='listsubcat',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('incharge', models.CharField(default='xwq', max_length=45)),
                ('catid', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Others',
            fields=[
                ('othersId', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=400)),
                ('compid', models.CharField(default='R', max_length=15)),
                ('fidate', models.DateField(default=datetime.datetime(2018, 11, 9, 0, 0))),
                ('status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compid', models.CharField(max_length=45)),
                ('text', models.CharField(max_length=255)),
                ('pub_date', models.DateField()),
                ('status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Sports',
            fields=[
                ('sportsId', models.AutoField(primary_key=True, serialize=False)),
                ('subcatId', models.IntegerField(default=0)),
                ('sportname', models.CharField(max_length=45)),
                ('nature', models.CharField(max_length=45)),
                ('description', models.CharField(max_length=400)),
                ('compid', models.CharField(default='R', max_length=15)),
                ('fidate', models.DateField(default=datetime.datetime(2018, 11, 9, 0, 0))),
                ('status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userRollNumber', models.BigIntegerField(unique=True)),
                ('userName', models.CharField(max_length=45)),
                ('UserMailId', models.CharField(default='@iiits.in', max_length=45)),
                ('Type', models.CharField(default='None', max_length=45)),
                ('lastloggedin', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complaint.Choice')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complaint.Poll')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complaint.User')),
            ],
        ),
        migrations.AddField(
            model_name='sports',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complaint.User'),
        ),
        migrations.AddField(
            model_name='poll',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complaint.User', to_field='userRollNumber'),
        ),
        migrations.AddField(
            model_name='others',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complaint.User'),
        ),
        migrations.AddField(
            model_name='latestotp',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complaint.User'),
        ),
        migrations.AddField(
            model_name='hostel',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complaint.User'),
        ),
        migrations.AddField(
            model_name='events',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complaint.User'),
        ),
        migrations.AddField(
            model_name='choice',
            name='poll',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='complaint.Poll'),
        ),
        migrations.AddField(
            model_name='academics',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complaint.User'),
        ),
    ]
